export interface IMenuItem {
  id?: string;
  icon?: string;
  label: string;
  to: string;
  newWindow?: boolean;
  subs?: IMenuItem[];
  roles?: [];
  permiso?: string;
  tipo_sucursal?: string;
  hr?: boolean;
}

const data: IMenuItem[] = [
  {
    icon: '../../assets/icon-menu/inicio.png',
    label: 'Inicio',
    to: `/dashboard`,
    roles: [],
    permiso: 'inicio.index',
    subs: [],
  },
  {
    icon: '../../assets/icon-menu/vender.png',
    label: 'Vender',
    to: `/vender/ventarestaurantebar`,
    roles: [],
    permiso: 'ventas.vender',
    tipo_sucursal: 'tipo_restaurante',
    subs: [],
  },
  {
    icon: '../../assets/icon-menu/vender.png',
    label: 'Vender',
    to: `/vender/ventatienda`,
    roles: [],
    permiso: 'ventas.vender',
    tipo_sucursal: 'tipo_tienda',
    subs: [],
  },

  {
    icon: '../../assets/icon-menu/inventario.png',
    label: 'Inventario',
    to: `/inventario_`,
    // roles: [UserRole.Editor],
    subs: [
      {
        icon: 'bx bx-grid-alt i',
        label: 'Bodegas',
        to: `/inventario/bodega`,
        permiso: 'inventario.bodegas',
        hr: false,
      },
      {
        icon: 'bx bx-grid-alt i',
        label: 'Categorías',
        to: `/inventario/categoriaproducto`,
        permiso: 'inventario.categoria',
        hr: false,
      },
      {
        icon: 'iconsminds-conference',
        label: 'Productos',
        to: `/inventario/producto`,
        permiso: 'inventario.productos',
        hr: false,
      },
      {
        icon: 'iconsminds-handshake',
        label: 'Baja existencias',
        to: `/inventario/productobajaexistencia`,
        permiso: 'inventario.baja_existencia',
        hr: false,
      },
      {
        icon: 'iconsminds-user',
        label: 'Inventario',
        to: `/inventario/verinventario`,
        permiso: 'inventario.inventario',
        hr: false,
      },
      {
        icon: 'iconsminds-books',
        label: 'Ajustes de inventario',
        to: `/inventario/ajusteinventario`,
        permiso: 'inventario.ajustes_inventario',
        hr: false,
      },
      {
        icon: 'bx bx-grid-alt i',
        label: 'Traslados entre bodegas',
        to: `/inventario/trasladoBodega`,
        permiso: 'inventario.traslado_bodega',
        hr: false,
      },
      {
        icon: 'bx bx-grid-alt i',
        label: 'Traslados entre sucursales',
        to: `/inventario/trasladoSucursal`,
        permiso: 'inventario.traslado_sucursal',
        hr: false,
      },
      {
        icon: 'iconsminds-box-close',
        label: 'Inventario categorías',
        to: `/inventario/inventarioporcategoria`,
        permiso: 'inventario.inventario_categoria',
        hr: false,
      },
      {
        icon: 'bx bx-grid-alt i',
        label: 'Promociones',
        to: `/promociones/listado`,
        permiso: 'inventario.promociones',
        hr: false,
      },
      {
        icon: 'bx bx-grid-alt i',
        label: 'Producción',
        to: `/inventario/produccion`,
        permiso: 'inventario.produccion',
        hr: false,
      },
      {
        icon: 'iconsminds-box-close',
        label: 'Seguimiento de productos',
        to: `/informe/seguimiento-producto`,
        permiso: 'inventario.seguimiento_producto',
        hr: false,
      },
    ],
  },
  {
    icon: '../../assets/icon-menu/compras.png',
    label: 'Compras',
    to: `/Compras`,
    subs: [
      {
        icon: 'iconsminds-gears',
        label: 'Nueva Compra',
        to: `/compras`,
        permiso: 'compras.store',
        hr: false,
      },
      {
        icon: 'iconsminds-gears',
        label: 'Historial Compra',
        to: `/informe-compras`,
        permiso: 'compras.index',
        hr: false,
      },
      {
        icon: 'iconsminds-user',
        label: 'Detalle de compras',
        to: `/informe-compras/detallecompras`,
        permiso: 'compras.index',
        hr: false,
      },
      {
        icon: 'iconsminds-gears',
        label: 'Créditos de compras',
        to: `/informe-compras/creditos`,
        permiso: 'compras.creditos',
        hr: false,
      },
      {
        icon: 'iconsminds-gears',
        label: 'Compras por categorias',
        to: `/informe-compras/compras-categorias`,
        permiso: 'compras.categorias',
        hr: false,
      },
      {
        icon: 'iconsminds-user',
        label: 'Devolucion, notas de ajustes',
        to: `/informe-compras/devoluciones`,
        //to: `/second-menu/supervisor`,
        permiso: 'compras.devoluciones',
        hr: false,
      },
      {
        icon: 'iconsminds-gears',
        label: 'Eventos RADIAN',
        to: `/informe-compras/radian`,
        permiso: 'compras.eventos_radian',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Comprobante Informe Diario',
        to: `/informe-compras/comprobanteInformeDiarioCompra`,
        permiso: 'compras.comprobante_informe_diario',
        hr: false,
      },
    ],

    // roles: [UserRole.Editor],
  },
  {
    icon: '../../assets/icon-menu/gastos.png',
    label: 'Gastos',
    to: `/second-menu/conf`,
    subs: [
      {
        icon: 'iconsminds-gears',
        label: 'Categorias',
        to: `/gasto/categoriagastos`,
        permiso: 'gastos.categoria',
        hr: false,
      },
      {
        icon: 'iconsminds-conference',
        label: 'Gastos / Egresos',
        to: `/gasto/historialgastos`,
        permiso: 'gastos.index',
        hr: false,
      },
      {
        icon: 'iconsminds-conference',
        label: 'Gastos por categorias',
        to: `/gasto/gastoporcategoria`,
        permiso: 'gastos.ver_por_categoria',
        hr: false,
      },
    ],
    // roles: [UserRole.Editor],
  },
  {
    icon: '../../assets/icon-menu/clientes.png',
    label: 'Clientes',
    to: `/cliente/listaclientes`,
    permiso: 'clientes.index',
    subs: [],

    // roles: [UserRole.Editor],
  },
  {
    icon: '../../assets/icon-menu/calendario.png',
    label: 'Nómina',
    to: `/informe/nominaElectronica`,
    permiso: 'clientes.index',
    subs: [],
  },
  {
    icon: '../../assets/icon-menu/informes.png',
    label: 'Informes',
    to: `/informes`,
    // roles: [UserRole.Editor],
    subs: [
      {
        icon: 'iconsminds-gears',
        label: 'Historial de ventas',
        to: `/informe/historialventa`,
        permiso: 'informes.historial_venta',
        hr: false,
      },
      {
        icon: 'iconsminds-conference',
        label: 'Estado de ventas',
        to: `/informe/estadoventa`,
        permiso: 'informes.estado_venta',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Detalle de ventas',
        to: `/informe/detalleventa`,
        //to: `/second-menu/proveedor`,
        permiso: 'informes.estado_venta',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Ventas por categorias',
        to: `/informe/ventasporcategoria`,
        //to: `/informe/ventacategoria`,
        permiso: 'informes.ventas_por_categoria',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Domicilios',
        to: `/vender/domicilios`,
        permiso: 'informes.domicilios',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Comisiones de ventas',
        to: `/informe/comisionesVenta`,
        permiso: 'informes.comision_venta',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Comprobante Informe Diario',
        to: `/informe/comprobanteInformeDiario`,
        permiso: 'informes.comprobante_informe_diario',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Impuestos',
        to: `/informe/impuestos`,
        //to: `/second-menu/proveedor`,
        permiso: 'informes.impuestos',
        hr: false,
      },
      {
        icon: 'iconsminds-handshake',
        label: 'Créditos y Plan Separe',
        to: `/informe/creditosventa`,
        //to: `/second-menu/contrato`,
        permiso: 'informes.credito_venta',
        hr: false,
      },
      {
        icon: 'iconsminds-user',
        label: 'Devolucion, Créditos y Débitos',
        to: `/informe/devoluciones`,
        //to: `/second-menu/supervisor`,
        permiso: 'informes.devoluciones',
        hr: false,
      },
      {
        icon: 'iconsminds-books',
        label: 'Cotizaciones',
        to: `/informe/cotizaciones`,
        //to: `/second-menu/categoria`,
        permiso: 'informes.cotizaciones',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Bancos',
        to: `/informe/bancos`,
        //to: `/informe/ventacategoria`,
        permiso: 'informes.bancos',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Utilidades',
        to: `/informe/utilidades`,
        //to: `/second-menu/proveedor`,
        permiso: 'informes.utilidades',
        hr: false,
      },

      {
        icon: 'iconsminds-factory-1',
        label: 'Cerrar caja',
        to: `/informe/cerrarcaja`,
        //to: `/second-menu/proveedor`,
        permiso: 'informes.cerrar_caja',
        hr: false,
      },
      {
        icon: 'iconsminds-factory-1',
        label: 'Historial de caja',
        to: `/informe/historialcaja`,
        //to: `/second-menu/proveedor`,
        permiso: 'informes.historial_caja',
        hr: false,
      }
    ],
  },
  {
    icon: '../../assets/icon-menu/configurar.png',
    label: 'Configuración',
    to: `/configuracion_`,
    // roles: [UserRole.Editor],
    subs: [
      /*  {
        icon: 'iconsminds-gears',
        label: 'rol',
        to: `/configuracion/roles`,
      }, */
      {
        icon: 'iconsminds-gears',
        label: 'Sucursal',
        to: `/configuracion/sucursal`,
        permiso: 'configuracion.sucursal',
        hr: false,
      },
      {
        icon: 'iconsminds-conference',
        label: 'Proveedores',
        to: `/configuracion/proveedor`,
        permiso: 'configuracion.proveedor',
        hr: false,
      },
      {
        icon: 'iconsminds-handshake',
        label: 'Usuarios',
        to: `/configuracion/user`,
        permiso: 'configuracion.usuario',
        hr: false,
      },
      {
        icon: 'iconsminds-user',
        label: 'Zonas',
        to: `/configuracion/zona`,
        permiso: 'configuracion.zona',
        hr: false,
      },
      {
        icon: 'iconsminds-books',
        label: 'Mesas',
        to: `/configuracion/mesa`,
        permiso: 'configuracion.mesa',
        hr: false,
      },
      {
        icon: 'iconsminds-books',
        label: 'Domiciliarios',
        to: `/configuracion/domiciliario`,
        permiso: 'configuracion.domiciliario',
        hr: false,
      },

      {
        icon: 'iconsminds-books',
        label: 'Empleados',
        to: `/configuracion/empleados`,
        permiso: 'configuracion.empleado',
        hr: false,
      },
      {
        icon: 'iconsminds-books',
        label: 'Tipos de retenciones',
        to: `/configuracion/tipo_retencion`,
        permiso: 'configuracion.tipo_retencion',
        hr: false,
      },

      /* {
        icon: 'iconsminds-love',
        label: 'Sistema de puntos',
        to: `/configuracion/puntos`,
      }, */
    ],
  },
];
export default data;
